version: 2

models:
  - name: dim_date
    columns:
      - name: date
        tests:
          - test_name: not_null
          - test_name: unique
      - name: date_key
        tests:
          - test_name: not_null
          - test_name: unique

  - name: dim_item
    columns:
      - name: item_id
        tests:
          - test_name: not_null
          - test_name: unique

  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - test_name: not_null
          - test_name: unique

  - name: fact_sales
    columns:
      - name: sales_order_id
        tests:
          - test_name: not_null

      - name: item_id
        tests:
          - test_name: not_null
          - test_name: relationships
            arguments:
              to: ref('dim_item')
              field: item_id

      - name: customer_id
        tests:
          - test_name: not_null
          - test_name: relationships
            arguments:
              to: ref('dim_customer')
              field: customer_id

      - name: date_key
        tests:
          - test_name: relationships
            arguments:
              to: ref('dim_date')
              field: date_key

  - name: fact_gl
    columns:
      - name: entry_id
        tests:
          - test_name: not_null
          - test_name: unique
      - name: date_key
        tests:
          - test_name: relationships
            arguments:
              to: ref('dim_date')
              field: date_key

  - name: fact_inventory_movement
    columns:
      - name: entry_id
        tests:
          - test_name: not_null
          - test_name: unique
      - name: item_id
        tests:
          - test_name: relationships
            arguments:
              to: ref('dim_item')
              field: item_id
      - name: date_key
        tests:
          - test_name: relationships
            arguments:
              to: ref('dim_date')
              field: date_key
