name: "erp_lakehouse"
version: "1.0.0"
config-version: 2

profile: "erp_lakehouse"
flags:
  use_managed_iceberg: true
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  erp_lakehouse:
    +materialized: table
    staging:
      +schema: silver
    marts:
      +schema: gold


